Classes/WebDev/AssigmentsManagement/Models/College.cs
namespace AssigmentsManagement.Models
{
    public class College
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public DateTime EstablishedDate { get; set; }
        public short Rank { get; set; }
    }
}

Classes/WebDev/AssigmentsManagement/Models/ErrorViewModel.cs
namespace AssigmentsManagement.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Classes/WebDev/AssigmentsManagement/Controllers/CollegeController.cs
using AssigmentsManagement.Data;
using AssigmentsManagement.Models;
using Microsoft.AspNetCore.Mvc;

public class CollegeController: Controller
{
    private readonly AssignmentMgmtDb _db;

    public CollegeController(AssignmentMgmtDb db)
    {
        _db = db;
    }

    public IActionResult Index()
    {
        var colleges = _db.Colleges.ToList();
        return View(colleges);
    }
    
    public IActionResult Add()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Add(College college)
    {
        // Save college
        _db.Colleges.Add(college);
        _db.SaveChanges();

        return RedirectToAction(nameof(Index)) ;
    }

    public IActionResult Edit(int id)
    {
        var collgeToEdit = _db.Colleges.Find(id);
        return View(collgeToEdit);
    }

    [HttpPost]
    public IActionResult Edit(College college)
    {
        // Save college
        _db.Colleges.Update(college);
        _db.SaveChanges();

        return RedirectToAction(nameof(Index));
    }
}

Classes/WebDev/AssigmentsManagement/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AssigmentsManagement.Models;

namespace AssigmentsManagement.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }
}

Classes/WebDev/AssigmentsManagement/Views/College/Add.cshtml
@model College

<form class="row g-3" asp-controller="College" asp-action="Add" method="post">
  <div class="col-md-4">
    <label asp-for="Name" class="form-label"></label>    
    <input class="form-control" asp-for="Name">
  </div>

 <div class="col-md-4">
    <label asp-for="EstablishedDate" class="form-label"></label>    
    <input class="form-control" asp-for="EstablishedDate">
  </div>

  <div class="col-md-4">
    <label asp-for="Rank" class="form-label"></label>    
    <input class="form-control" asp-for="Rank">
  </div>

  <div class="col-12">
    <label asp-for="Address" class="form-label"></label>    
    <input class="form-control" asp-for="Address">
  </div>

  <div class="col-12">
    <label asp-for="Description" class="form-label"></label>    
    <textarea class="form-control" asp-for="Description"></textarea>
  </div>
  
  <div class="col-12">
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>

Classes/WebDev/AssigmentsManagement/Views/College/Edit.cshtml
@model College

<form class="row g-3" asp-controller="College" asp-action="Edit" method="post">
  <div class="col-md-4">
    <label asp-for="Name" class="form-label"></label>    
    <input class="form-control" asp-for="Name">
  </div>

 <div class="col-md-4">
    <label asp-for="EstablishedDate" class="form-label"></label>    
    <input class="form-control" asp-for="EstablishedDate">
  </div>

  <div class="col-md-4">
    <label asp-for="Rank" class="form-label"></label>    
    <input class="form-control" asp-for="Rank">
  </div>

  <div class="col-12">
    <label asp-for="Address" class="form-label"></label>    
    <input class="form-control" asp-for="Address">
  </div>

  <div class="col-12">
    <label asp-for="Description" class="form-label"></label>    
    <textarea class="form-control" asp-for="Description"></textarea>
  </div>
  
  <div class="col-12">
    <button type="submit" class="btn btn-primary">Update</button>
  </div>
</form>

Classes/WebDev/AssigmentsManagement/Views/College/Index.cshtml
@model List<College>

<h3>All Colleges</h3>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Address</th>
            <th scope="col">Established</th>
            <th scope="col">Rank</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach (var college in Model)
        {
            <tr>
                <th scope="row">@(i++)</th>
                <td>@college.Name</td>
                <td>@college.Description</td>
                <td>@college.Address</td>
                <td>@college.EstablishedDate</td>
                <td>@college.Rank</td>
                <th>
                    <a class="btn btn-warning btn-sm" href="/college/edit/@college.Id">Edit</a>
                    <a class="btn btn-danger btn-sm" href="/college/delete/@college.Id">Delete</a>
                </th>
            </tr>
        }
    </tbody>
</table>

Classes/WebDev/AssigmentsManagement/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Classes/WebDev/AssigmentsManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AssigmentsManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AssigmentsManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/home/index">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            College
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="/college/index">List</a></li>
            <li><a class="dropdown-item" href="/college/add">Add New College</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AssigmentsManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>